# Generated by Django 4.0.4 on 2022-05-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_criacao',
            field=models.DateField(default=None, null=True),
        ),
    ]
